"""The measured safe pusher workspace, an annulus about the iiwa base.

Every number here traces to workspace_map.json, generated by a dense nonlinear
IK mapping pass on the real controller plant rather than guessed. The region's
shape is physical: the inner rim is the J4 elbow limit, the outer rim is the
arm-extension reach circle.

project maps any candidate target to the nearest point of the safe region, so
an integrated gamepad command cannot wander into DiffIK-infeasible territory
(no windup, immediate reversal).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

_MAP_DIR = Path(__file__).resolve().parent
_MAP_FILES = {
    "zeng_canonical": "workspace_map.json",
    "workspace_optimized": "workspace_map_workspace_optimized.json",
}
_MAP_PATH = _MAP_DIR / _MAP_FILES["zeng_canonical"]

#: The base-placement profiles that have a certified map. Public because the
#: station needs to ask whether a profile has a schedule without reaching into
#: module privates; see nominal_schedule below.
PROFILES: tuple[str, ...] = tuple(_MAP_FILES)


def map_path(profile: str) -> Path:
    """Absolute path of a profile's certified map file.

    The maps live beside this module and are resolved relative to it, so their
    location is encoded here instead of in a Path(workspace.__file__).parent at
    each call site.
    """
    if profile not in _MAP_FILES:
        raise ValueError(f"unknown profile {profile!r}; known: {sorted(_MAP_FILES)}")
    return _MAP_DIR / _MAP_FILES[profile]


def load_map(profile: str) -> dict:
    """The whole certified-map payload: safe region, provenance, schedule."""
    return json.loads(map_path(profile).read_text())


def nominal_schedule(
    profile: str,
) -> tuple[list, list, tuple[float, float, float]] | None:
    """(radii, postures, base_pose) for the DiffIK joint-centering nominal.

    Returns None when the profile is unknown, and also when its map carries no
    schedule; zeng_canonical is the latter case, where a constant nominal is the
    correct behaviour. A missing map file instead raises FileNotFoundError,
    because that is a broken installation rather than a profile without a
    schedule, and the two must not be conflated. The station relies on exactly
    these three behaviours (pusht_drake.sim.station).
    """
    if profile not in _MAP_FILES:
        return None
    payload = json.loads((_MAP_DIR / _MAP_FILES[profile]).read_text())
    schedule = payload.get("nominal_schedule")
    if schedule is None:
        return None
    base = payload.get("base_pose", [0.0, 0.0, 0.0])
    return (
        schedule["radii"],
        schedule["postures"],
        (float(base[0]), float(base[1]), float(base[2])),
    )


@dataclass(frozen=True)
class SafeWorkspace:
    """The safe region, defined in the robot base frame.

    r, y and the azimuth limit are all base-relative; base places that region in
    the world. With base = (0, 0, 0), the zeng_canonical profile where the iiwa
    is welded at the world origin, base and world frames coincide. az_max
    (joint 1's working range) is the physical limit on azimuth; the y bounds are
    an artifact of the mapper's sampling window, kept so the canonical profile
    stays bit-identical.

    x_min/x_max are the same sampling window in the other axis, and they are
    not cosmetic: az_max is joint 1's mechanical limit (160 deg), but the mapper
    never sampled past ~56 deg (zeng_canonical) or ~103 deg (workspace_optimized).
    Without an x bound the region extrapolates into a lobe behind the robot that
    no IK solve ever validated, and project would send teleop commands there.
    Both bounds are the sampled range eroded by the map's erosion_m, exactly as
    the y bounds are.
    """

    r_min: float
    r_max: float
    y_min: float
    y_max: float
    az_max: float = np.pi
    base: tuple[float, float, float] = (0.0, 0.0, 0.0)
    x_min: float = -np.inf
    x_max: float = np.inf

    @classmethod
    def load(cls, path: Path | None = None, profile: str = "zeng_canonical") -> SafeWorkspace:
        if path is None:
            if profile not in _MAP_FILES:
                raise ValueError(f"unknown profile {profile!r}; known: {sorted(_MAP_FILES)}")
            path = _MAP_DIR / _MAP_FILES[profile]
        payload = json.loads(path.read_text())
        region = payload["safe_region"]
        base = payload.get("base_pose", [0.0, 0.0, 0.0])
        return cls(
            r_min=float(region["r_min"]),
            r_max=float(region["r_max"]),
            y_min=float(region["y_min"]),
            y_max=float(region["y_max"]),
            az_max=float(region.get("az_max", np.pi)),
            base=(float(base[0]), float(base[1]), float(base[2])),
            x_min=float(region.get("x_min", -np.inf)),
            x_max=float(region.get("x_max", np.inf)),
        )

    # -- frame helpers ------------------------------------------------------

    def to_base(self, xy) -> np.ndarray:
        dx = float(xy[0]) - self.base[0]
        dy = float(xy[1]) - self.base[1]
        c, s = np.cos(-self.base[2]), np.sin(-self.base[2])
        return np.array([c * dx - s * dy, s * dx + c * dy])

    def to_world(self, xy_base) -> np.ndarray:
        c, s = np.cos(self.base[2]), np.sin(self.base[2])
        x, y = float(xy_base[0]), float(xy_base[1])
        return np.array([c * x - s * y + self.base[0], s * x + c * y + self.base[1]])

    def contains(self, xy, tol: float = 0.0) -> bool:
        p = self.to_base(xy)
        r = float(np.hypot(p[0], p[1]))
        az = abs(float(np.arctan2(p[1], p[0])))
        return (
            self.r_min - tol <= r <= self.r_max + tol
            and self.y_min - tol <= p[1] <= self.y_max + tol
            and self.x_min - tol <= p[0] <= self.x_max + tol
            and az <= self.az_max + tol
        )

    def project(self, xy) -> np.ndarray:
        """Nearest point of the region, computed in the base frame.

        Radial clamp, then azimuth clamp, then the y clamp, iterated because
        each can move a point off the constraint the previous one satisfied. Two
        passes reach a fixed point for this geometry (annulus sector intersected
        with a y-slab, all containing the region's bulk).
        """
        p = self.to_base(xy)
        for _ in range(2):
            r = float(np.hypot(p[0], p[1]))
            if r < 1e-9:
                p = np.array([self.r_min, 0.0])
                r = self.r_min
            if r < self.r_min:
                p *= self.r_min / r
            elif r > self.r_max:
                p *= self.r_max / r
            az = float(np.arctan2(p[1], p[0]))
            if abs(az) > self.az_max:
                r = float(np.hypot(p[0], p[1]))
                az = np.clip(az, -self.az_max, self.az_max)
                p = np.array([r * np.cos(az), r * np.sin(az)])
            p[1] = min(max(p[1], self.y_min), self.y_max)
            p[0] = min(max(p[0], self.x_min), self.x_max)
        return self.to_world(p)


def boundary_polyline(workspace: SafeWorkspace, points_per_arc: int = 240) -> np.ndarray:
    """The closed boundary of the safe region as an (N, 2) polyline in world coordinates.

    Derived from the same SafeWorkspace instance the teleop guard projects
    against, so the drawn fence and the enforced fence cannot disagree.

    The region is {r in [r_min, r_max]} & {y in [y_min, y_max]} & {|az| <= az_max},
    all in the base frame. Rather than special-casing which constraint clips which
    arc, the boundary is swept by azimuth: at each azimuth the region is the radial
    interval [r_min, r_hi(az)], where r_hi is r_max clipped by whichever
    slab edge the ray meets first. Tracing the outer edge one way and the inner edge
    back gives a closed loop that is correct for any combination of the bounds, and
    that follows the slab edge instead of cutting across the interior with a chord
    wherever the slab clips.

    The base-to-world conversion at the end is not optional: the two frames are
    1.1 m apart on workspace_optimized, and coincide only on zeng_canonical,
    whose base is the world origin.
    """
    ws = workspace

    def radial_span(az: float):
        """(r_lo, r_hi) at this azimuth, or None if the azimuth is entirely outside."""
        s_az = np.sin(az)
        r_hi = ws.r_max
        if s_az > 1e-12:
            r_hi = min(r_hi, ws.y_max / s_az)
        elif s_az < -1e-12:
            r_hi = min(r_hi, ws.y_min / s_az)
        # ... and by the sampled-domain x bounds, the same way.
        c_az = np.cos(az)
        if c_az > 1e-12:
            r_hi = min(r_hi, ws.x_max / c_az)
        elif c_az < -1e-12:
            r_hi = min(r_hi, ws.x_min / c_az)
        r_lo = ws.r_min
        # The inner rim itself can fall outside the slab or the x window here.
        y_lo, x_lo = r_lo * s_az, r_lo * c_az
        if not (ws.y_min <= y_lo <= ws.y_max and ws.x_min <= x_lo <= ws.x_max):
            return None
        if r_hi < r_lo:
            return None
        return r_lo, r_hi

    azimuths = np.linspace(-ws.az_max, ws.az_max, points_per_arc)
    spans = [(a, radial_span(a)) for a in azimuths]
    live = [(a, sp) for a, sp in spans if sp is not None]
    if not live:
        return np.empty((0, 2))

    outer = np.array([[sp[1] * np.cos(a), sp[1] * np.sin(a)] for a, sp in live])
    inner = np.array([[sp[0] * np.cos(a), sp[0] * np.sin(a)] for a, sp in reversed(live)])
    loop = np.vstack([outer, inner, outer[:1]])
    return np.array([ws.to_world(p) for p in loop])


def add_workspace_boundary_visualization(
    meshcat,
    workspace: SafeWorkspace | None = None,
    *,
    path: str = "workspace/safe_boundary",
    z_m: float = 0.0015,
    line_width: float = 2.0,
) -> None:
    """Draw the safe-region boundary in Meshcat: thin green lines, no fill.

    Visualization only; a Meshcat line object has no collision geometry and no
    plant presence. Drawn ~1.5 mm above the tabletop (world z = 0) to avoid
    z-fighting with the table surface.
    """
    from pydrake.all import Rgba

    ws = workspace or SafeWorkspace.load()
    loop = boundary_polyline(ws)  # already world coordinates
    vertices = np.vstack([loop.T, np.full(len(loop), z_m)])  # 3 x N
    meshcat.SetLine(path, vertices, line_width=line_width, rgba=Rgba(0.1, 0.85, 0.25, 1.0))
